import type { Metadata } from "next";
import { Heebo } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

const font = Heebo({
	subsets: ["latin"],
	variable: "--font-main",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className={`${font.variable} font-sans`}>
			<body className='bg-background w-full flex justify-center'>{children}</body>
			<div className='absolute bottom-44 right-[5em] bg-background w-[500px] h-[400px] rounded-full blur-3xl bg-blue-400 opacity-70 -z-10'></div>
			<div className='absolute -bottom-16 -left-[10em] bg-background w-[700px] h-[300px] rounded-full blur-3xl bg-gray-400 opacity-70 -z-10'></div>
			<svg className='hidden'>
				<filter id='noiseFilter'>
					<feTurbulence type='fractalNoise' baseFrequency='0.5' stitchTiles='stitch' />
					<feColorMatrix in='colorNoise' type='matrix' values='1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0' />
					<feComposite operator='in' in2='SourceGraphic' result='monoNoise' />
					<feBlend in='SourceGraphic' in2='monoNoise' mode='screen' />
				</filter>
			</svg>
			<Toaster />
		</html>
	);
}
